# -*- coding: utf-8 -*-
"""yolov5 cancer dection.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1IKx31m-Hin6GtOm-sgNtNdM8y8W2BiZ_
"""

# Commented out IPython magic to ensure Python compatibility.
!git clone https://github.com/ultralytics/yolov5
# %cd yolov5
# %pip install -qr requirements.txt comet_ml

import torch
import utils
display = utils.notebook_init()

!pip install roboflow

from roboflow import Roboflow
rf = Roboflow(api_key="npNt7sdH4987TNeCPwGR")
project = rf.workspace("g-hacker-ezcxb").project("breast-cancer-jq1sj")
dataset = project.version(1).download("yolov5")

!python /content/yolov5/detect.py --weights yolov5s.pt --img 640 --conf 0.25 --source /content/breast-cancer-1/test/images

!python /content/yolov5/train.py --img 416 --batch 16 --epochs 150 --data {/content/breast-cancer-1/train/images}/data.yaml --weights yolov5s.pt --cache

from roboflow import Roboflow

rf = Roboflow(model_format="yolov5" , notebook="ultralytics")

import os as mk

from os import environ

mk.enveron["DATASET_DIRECTORY"] = "/content/breast-cancer-1"